# Numpy

In [1]:
import numpy as np

Créez à partir d’une liste un array unidimensionnel et vérifiez sa taille et ce qu’il comporte.


In [2]:
arr1=np.array([3,4,7])


In [3]:
print(arr1.dtype)

int32


In [4]:
print(arr1.shape)

(3,)


Générez des arrays remplis de 0 et de 1 de taille 10.


In [5]:
arr2=np.zeros(10)
arr3=np.ones(10)
arr4=np.full(10,5.0)

In [6]:
#les additions se font termes à termes
print(arr4+arr3)

[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]


In [7]:
#on extrait le 5ème élément de l'array
arr4[4]

5.0

In [8]:
#on génère 11 points entre 0 et 5
np.linspace(0,5,11)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [9]:
#on génère une suite de points entre 0 et 5 tout les 0.5
np.arange(0,5.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [10]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [11]:
#on génère un array de dimension 2
arr5=np.array([[4,5,6],[2,3,4]])

In [12]:
#on reshape un array de dimension 1 en un array de dimension 2
arr6=np.linspace(0,4.5,10).reshape(2,5)

In [13]:
#on calcule le cube de chaque cellule de l'array
print(arr6**3)

[[  0.      0.125   1.      3.375   8.   ]
 [ 15.625  27.     42.875  64.     91.125]]


Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.


In [14]:
arr7=np.arange(5,11).reshape(3,2)
arr7

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
np.dot(arr7.T,arr7)

array([[155, 176],
       [176, 200]])

Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [16]:
arr8=np.random.randn(10000000)

In [17]:
print(arr8.shape,arr8.mean(),arr8.var())

(10000000,) -0.000236611370302 0.999682465598


In [18]:
arr8=np.where(arr8>0,arr8,0)
arr8=np.sort(arr8)

In [19]:
print(arr8.shape,arr8.mean(),arr8.var())

(10000000,) 0.39871736399 0.340728728626


In [20]:
arr8.sort()
print(arr8)

[ 0.          0.          0.         ...,  5.06273596  5.07601165
  5.33238096]


Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt


In [21]:
arr9=np.random.randn(10000000).reshape(100000,100)

In [22]:
%time np.save("arr9.npy",arr9)

Wall time: 239 ms


In [23]:
%time np.savetxt("arr9.txt",arr9)

Wall time: 9.43 s


In [24]:
del arr9

In [25]:
arr9=np.load("arr9.npy")

In [26]:
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    3: 3 elems, type `int32`, 12 bytes
arr2       ndarray    10: 10 elems, type `float64`, 80 bytes
arr3       ndarray    10: 10 elems, type `float64`, 80 bytes
arr4       ndarray    10: 10 elems, type `float64`, 80 bytes
arr5       ndarray    2x3: 6 elems, type `int32`, 24 bytes
arr6       ndarray    2x5: 10 elems, type `float64`, 80 bytes
arr7       ndarray    3x2: 6 elems, type `int32`, 24 bytes
arr8       ndarray    10000000: 10000000 elems, type `float64`, 80000000 bytes (76.2939453125 Mb)
arr9       ndarray    100000x100: 10000000 elems, type `float64`, 80000000 bytes (76.2939453125 Mb)
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
